# Welcome to Jekyll!

# Site settings
title: DrupalTools
email:
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://drupaltools.com" # the base hostname & protocol for your site
copyright: '<a href="https://www.drupal.org">Drupal</a> is a <a href="http://drupal.com/trademark">registered trademark</a> of <a href="http://buytaert.net">Dries Buytaert</a>.'

# Build settings
markdown: kramdown

# GitHub Pages compatible settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - mcp-package
  - api

# yml_files = Dir.glob("_data/projects/*.yml")
# puts "page_gen:"
# yml_files.each do |file|
#   puts <<EOS
#   - data: #{file.gsub("_data", "").gsub(".yml", "")}
#     name: name
#     template: project
#     dir: projects
#     index_files: false
# EOS
# end

sass:
  style: "compressed"
  sass_dir: _sass
